packages:
  - packages/*
  - playground

catalog:
  '@ant-design/colors': ^7.2.1
  '@ant-design/fast-color': ^3.0.0
  '@antfu/eslint-config': ^5.3.0
  '@vitejs/plugin-vue': ^6.0.1
  '@vue/tsconfig': ^0.7.0
  eslint: ^9.35.0
  h3: 2.0.0-beta.4
  jiti: ^2.5.1
  less: ^4.4.1
  mock-h3: 0.0.1-beta.12
  tsdown: ^0.14.2
  typescript: ~5.8.3
  unplugin-vue: ^7.0.1
  unplugin-vue-router: ^0.15.0
  vite: ^7.1.2
  vue: ^3.5.18
  vue-router: ^4.5.1
  vue-tsc: ^3.0.5

onlyBuiltDependencies:
  - esbuild
