packages:
  - packages/*
  - playground

catalog:
  '@ant-design/colors': ^7.2.1
  '@ant-design/fast-color': ^3.0.0
  '@ant-design/icons-vue': ^7.0.1
  '@antfu/eslint-config': ^5.3.0
  '@types/fs-extra': ^11.0.4
  '@types/jsdom': ^21.1.7
  '@types/node': ^24.3.3
  '@v-c/color-picker': ^1.0.0
  '@v-c/util': ^0.0.4
  '@vitejs/plugin-vue': ^6.0.1
  '@vue/test-utils': ^2.4.6
  '@vue/tsconfig': ^0.7.0
  '@vueuse/core': ^13.9.0
  es-toolkit: ^1.39.10
  eslint: ^9.35.0
  eslint-plugin-format: ^1.0.1
  esno: ^4.8.0
  fs-extra: ^11.3.1
  h3: 2.0.0-beta.4
  jiti: ^2.5.1
  jsdom: ^26.1.0
  less: ^4.4.1
  mock-h3: 0.0.1-beta.12
  tsdown: ^0.14.2
  typescript: ~5.8.3
  unocss: ^66.5.1
  unplugin-vue: ^7.0.1
  unplugin-vue-router: ^0.15.0
  vite: ^7.1.5
  vite-plugin-inspect: ^11.3.3
  vitest: ^3.2.4
  vue: ^3.5.21
  vue-router: ^4.5.1
  vue-tsc: ^3.0.7

onlyBuiltDependencies:
  - esbuild
  - vue-demi
