export type { AffixProps } from './affix'
export type { AlertProps } from './alert'
export type { AnchorProps } from './anchor'
export type { ButtonProps } from './button'
export type { SizeType } from './config-provider/size-context'
export type { SpaceCompactItemProps, SpaceCompactProps, SpaceProps } from './space'
